### ISSUE TITLE
What do you mean by flexible width in TODO's

### ISSUE THREAD

**Issue by vigneshshanmugam** [andydavies/waterfall#9]
Will submit a PR once I am clear with this.

**Comment by vigneshshanmugam** [comment]
https://github.com/vigneshshanmugam/waterfall/commit/e0f1b95ee2690eaa192a46a6d2cde13943514618

Not sure whether you meant that.

**Comment by andydavies** [comment]
Yes, exactly that perhaps with a margin on the left and right hand sides

**Comment by vigneshshanmugam** [comment]
Sure will raise a PR with the fix.

**Comment by vigneshshanmugam** [comment]
Created a PR  #10
